jobs:
  build:
    docker:
      - image: cimg/rust:1.52.1
    steps:
      - checkout
      - run: |
          sudo apt update && sudo apt install -y pkg-config libssl-dev
          cargo fmt --all -- --check
          cargo clippy
          cargo test -- verbose
  docker:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/386,linux/arm/v7
      IMAGE_NAME: ozamosi/tilted
    steps:
      - checkout
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            sudo swapon --show
            sudo dd if=/dev/zero of=/swapfile1 bs=1M count=6K
            sudo chmod 600 /swapfile1
            sudo mkswap /swapfile1
            sudo swapon /swapfile1
            sudo swapon --show
            sudo free -h
            sudo systemctl stop docker
            sudo mount -t tmpfs -o size=9G tmpfs /var/lib/docker
            df -h
            sudo systemctl start docker

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run:
          name: Build
          command: |
            docker buildx create --name mybuilder --use
            docker buildx build --platform ${BUILDX_PLATFORMS} --tag ${IMAGE_NAME}:edge --tag ${IMAGE_NAME}:${CIRCLE_SHA1} .
      - run:
          name: Push
          command: |
            docker push ${IMAGE_NAME}:edge ${IMAGE_NAME}:${CIRCLECI_SHA1}
          filters:
            branch:
              master
      - run:
          name: Tag release
          command: |
            docker tag ${IMAGE_NAME}:edge ${IMAGE_NAME}:${CIRCLECI_TAG}
            docker push ${IMAGE_NAME}:${CIRCLECI_TAG}
          filters:
            tags:
              only: /^v.*/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - docker
